#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SayIt_TextToSpeech.Resource", IsApplication=true)]

namespace SayIt_TextToSpeech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_git = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int btnSpeak = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int editSpeech = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int lblLanguage = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int lblPitch = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int lblSayText = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int lblSpeed = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int linearLayoutButtons = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int linearLayoutConfig = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int linearLayoutText = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int menu_config = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int menu_git = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int seekPitch = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int seekSpeed = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int spinLanguage = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int tableLayoutConfig = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tableRow1 = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int tableRow2 = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow3 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int textPitch = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int textSpeed = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int textView14 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int configTTS = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int git = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int language = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int pitch = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int say_button = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int say_input = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int say_label = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int share = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int share_by = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int speed = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
