#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SayIt_TextToSpeech.Resource", IsApplication=true)]

namespace SayIt_TextToSpeech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_git = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int btnClear = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int btnShare = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btnSpeak = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int editSpeech = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int lblLanguage = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int lblPitch = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int lblSayText = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int lblSpeed = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int linearLayoutButtons = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int linearLayoutConfig = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int linearLayoutText = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int menu_config = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int menu_git = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int seekPitch = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int seekSpeed = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int spinLanguage = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int tableLayoutConfig = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int tableRow1 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int tableRow2 = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int tableRow3 = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int textPitch = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int textSpeed = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int textView14 = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int clear = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int configTTS = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int file_location = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int git = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int language = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int no_text = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int pitch = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int save_error = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int say_button = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int say_error = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int say_input = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int say_label = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int share = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int share_by = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int speed = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
