#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SayIt_TextToSpeech.Resource", IsApplication=true)]

namespace SayIt_TextToSpeech
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040012
			public const int btnSpeak = 2130968594;
			
			// aapt resource value: 0x7f040002
			public const int editSpeech = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lblSayText = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int linearLayout2 = 2130968579;
			
			// aapt resource value: 0x7f040011
			public const int linearLayout3 = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int linearLayoutMain = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int seekPitch = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int seekSpeed = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int spinLanguage = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int tableLayout1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int tableRow1 = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int tableRow2 = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int tableRow3 = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int textPitch = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int textSpeed = 2130968592;
			
			// aapt resource value: 0x7f040006
			public const int textView11 = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int textView12 = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int textView13 = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int textView14 = 2130968584;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int say_button = 2130903043;
			
			// aapt resource value: 0x7f030002
			public const int say_input = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int say_label = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
